# coding: utf-8
	Vaccine.create({name: "なし"})
	Vaccine.create({name: "黄熱病"})
	Vaccine.create({name: "A型肝炎"})
	Vaccine.create({name: "B型肝炎"})
	Vaccine.create({name: "破傷風"})
	Vaccine.create({name: "狂犬病"})
	Vaccine.create({name: "ポリオ"})
	Vaccine.create({name: "日本脳炎"})
	Vaccine.create({name: "麻疹風疹"})
	Vaccine.create({name: "不明"})
